Chatroom starts and connects to fastify. fastify waits for nginx to launch first, and chatroom waits for fastify to launch

diff --git a/srcs/chatroom/Dockerfile b/srcs/chatroom/Dockerfile
--- a/srcs/chatroom/Dockerfile
+++ b/srcs/chatroom/Dockerfile
@@ -1,18 +1,18 @@
 FROM debian:bullseye
 
+RUN if [ -z "${BACKEND_PORT}'" ]; then echo "ERROR: BACKEND_PORT is not set" >&2; exit 1; fi
+RUN if [ -z "${BACKEND_NAME}'" ]; then echo "ERROR: BACKEND_NAME is not set" >&2; exit 1; fi
+
 RUN mkdir -p /chatroom/
 
-COPY chatroom_core/ /chatroom/
-RUN chmod -R 755 /chatroom/
+WORKDIR /chatroom/
 
-# RUN apt-get update && apt-get install g++ build-essential libwebsocketpp-dev -y && rm -rf /var/lib/apt/lists/*
+# Dont want to move objs or the executable.
+COPY chatroom_core/ .
+RUN chmod -R 755 .
 
-#wscat/nodejs for debugging only
-RUN apt-get update && apt-get install g++ build-essential libwebsocketpp-dev nodejs npm -y && rm -rf /var/lib/apt/lists/*
+RUN apt-get update && apt-get install g++ build-essential libwebsocketpp-dev libssl-dev libboost-all-dev -y && rm -rf /var/lib/apt/lists/*
 
-RUN npm install -g wscat
+RUN make re
 
-COPY eternal.sh /chatroom/
-RUN chmod 777 eternal.sh
-
-RUN bash eternal.sh
+CMD ./chatroom_exec ws://$BACKEND_NAME:$BACKEND_PORT/ws
diff --git a/srcs/nginx/Dockerfile b/srcs/nginx/Dockerfile
--- a/srcs/nginx/Dockerfile
+++ b/srcs/nginx/Dockerfile
@@ -1,16 +1,18 @@
 FROM nginx:1.29.0
 
+RUN if [ -z "${TR_NETWORK_SUBNET}'" ]; then echo "ERROR: TR_NETWORK_SUBNET is not set" >&2; exit 1; fi
+
 RUN apt-get update && apt-get install -y gettext openssl procps && rm -rf /var/lib/apt/lists/*
 
 # HEALTHCHECK --interval=5s --timeout=2s --retries=3 CMD nginx -t
 
-COPY nginx.conf /etc/nginx/
-RUN chmod 644 /etc/nginx/nginx.conf
+RUN mkdir -p /etc/nginx/un_expanded/
+COPY nginx.conf.to_expand /etc/nginx/un_expanded
+RUN chmod 644 /etc/nginx/un_expanded/nginx.conf.to_expand
 
-# Make site-templates and move things awaiting nginx_entryp.sh to replace env vars within the files.
-RUN mkdir -p /etc/nginx/site-templates/
-COPY mysite.conf.to_expand /etc/nginx/site-templates
-RUN chmod 644 /etc/nginx/site-templates/mysite.conf.to_expand
+# Make un_expanded and move things awaiting nginx_entryp.sh to replace env vars within the files.
+COPY mysite.conf.to_expand /etc/nginx/un_expanded
+RUN chmod 644 /etc/nginx/un_expanded/mysite.conf.to_expand
 
 RUN rm -f /etc/nginx/conf.d/default.d
 
